name: miniF2F_test_subset
num_files: 1
language: LEAN
few_shot_data_path_for_retrieval:
few_shot_metadata_filename_for_retrieval:
dfs_data_path_for_retrieval:
dfs_metadata_filename_for_retrieval:
datasets:
  - project: testbed
    files:
      - path: src/miniF2F_test.lean
        theorems:
        - aime_1983_p1
        - aime_1983_p3
        - aime_1984_p7
        - aime_1988_p8
        - aime_1999_p11
        - algebra_absapbon1pabsapbleqsumabsaon1pabsa
        - algebra_apbon2pownleqapownpbpowon2
        - algebra_sqineq_at2malt1
        - algebra_sum1onsqrt2to1onsqrt10000lt198
        - algebra_2varlineareq_fp3zeq11_3tfm1m5zeqn68_feqn10_zeq7
        - mathd_algebra_129
        - mathd_algebra_148
        - mathd_algebra_209
        - mathd_algebra_338